version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package spring-boot:repackage
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - '**/*'
  base-directory: 'build'