version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package spring-boot:repackage
      - mv target/BookRentalAppSpboot-0.0.1-SNAPSHOT.jar BookRentalAppSpboot-0.0.1-SNAPSHOT.jar
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - BookRentalAppSpboot-0.0.1-SNAPSHOT.jar
  discard-paths: yes